export const aboutObj1 = {
  id: 'aboutObj1',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Why Us',
  headline: 'Why Choose Charismatic Electronics?',
  description: 'At Charismatic Electronics, we are committed not only to providing quality, timely delivery, and competitive prices, but also to understanding the complexities of manufacturing and design. Backed by a sound financial foundation, we ensure our reliability as a preferred supply chain partner for all OEMs and ODMs.',
  buttonLabel: '',
  imgStart: false,
  img: '',
  alt: '',
  dark: false,
  primary: false,
  darkText: true,
};

export const aboutObj2 = {
  id: 'aboutObj2',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'Our Vision',
  headline: 'Empowering Growth with Trust',
  description: [
    '• We aspire to be a charismatic organization that manufactures and markets products and services that enhance value for customers, partners, employees, and society.',
    '• We are a vibrant team that passionately serves customers, learns continuously, and fosters a collaborative, growth-oriented culture.',
    '• We are committed to improving the lives of all stakeholders by ensuring long-term growth, trust, and mutual benefit.',
  ],
  buttonLabel: '',
  imgStart: true,
  img: '',
  alt: '',
  dark: true,
  primary: true,
  darkText: false,
};

export const aboutObj3 = {
  id: 'aboutObj3',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Core Values',
  headline: 'CHEL Core Values',
  description: [
    '• Growth of associates working in the organization',
    '• Exceeding customer expectation & adding value to their business',
    '• Implementing best practices of different industries in Ferrite magnetics business',
    '• Innovation',
  ],
  buttonLabel: '',
  imgStart: false,
  img: '',
  alt: '',
  dark: false,
  primary: false,
  darkText: true,
};

export const aboutObj4 = {
  id: 'aboutObj4',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'Quality Policy',
  headline: 'Reliable. Efficient. Customer-Centric.',
  description: [
    'We are committed to become most preferred supplier of our valued customers by providing quality products, consistently meeting their needs and expectations.',
    'This shall be achieved by:', 
    '• Improving Productivity and controlling Rejections',
    '• Adhering to delivery commitments',
    '• Developing skilled & competent manpower',
    '• Managing Inventory',
    '• Complying with applicable requirements',
    '• Continually improving effectiveness of QMS',
    'Customer Satisfaction is our topmost priority.',
  ],
  buttonLabel: '',
  imgStart: true,
  img: '',
  alt: '',
  dark: true,
  primary: true,
  darkText: false,
};

export const aboutObj5 = {
  id: 'aboutObj5',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Manufacturing Capabilities',
  headline: 'Winding, Automation, Testing, Quality, Exports',
  description: [
    '• Knowledge of best working practices in Automobile, Consumer Durable, Electronic & Telecom Industries — including Toyota Production System, JIT, TPM, and Industrial Engineering. Experience with high-volume production and exports to China, Korea, and the Philippines.',
    '• Expertise in manufacturing machines for wound components such as semi-automatic winding machines, taping machines, temperature-controlled dip soldering units, automatic transformer testers, high-voltage testing, insulation resistance testing, micrometers, vernier calipers, ammeters, and voltmeters.',
    '• Robust quality systems implemented across Incoming, In-Process, and Outgoing stages to ensure consistent product excellence.'
  ],  
  buttonLabel: '',
  imgStart: false,
  img: '',
  alt: '',
  dark: false,
  primary: false,
  darkText: true,
};

export const aboutObj6 = {
  id: 'aboutObj6',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'Technical Capabilities',
  headline: 'Built to Perform: Sustainable, Safe & Standards-Compliant"',
  description:[
    '• High Voltage up to 5KV, 60 Sec',
    '• Insulation Resistance up to 100 MΩ',
    '• RoHS compliance',
    '• UL compliance',
    '• FR Products',
    '• High Temperature compliance'
  ],
  buttonLabel: '',
  imgStart: true,
  img: '',
  alt: '',
  dark: true,
  primary: true,
  darkText: false,
};

export const aboutObj7 = {
  id: 'aboutObj7',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Industries Served',
  headline: 'Powering Innovation Across Industries',
  description:[
    '• Aerospace',
    '• Mobile Phone',
    '• Air Conditioning',
    '• Water Purifier',
    '• Security Products',
    '• Electrical Vehicles',
    '• Lightening',
  ],
  buttonLabel: '',
  imgStart: false,
  img: '',
  alt: '',
  dark: false,
  primary: false,
  darkText: true,
};
